# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 154)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.name_Label = QtWidgets.QLabel(self.centralwidget)
        self.name_Label.setText("")
        self.name_Label.setObjectName("name_Label")
        self.gridLayout_2.addWidget(self.name_Label, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.VolumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.VolumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.VolumeSlider.setObjectName("VolumeSlider")
        self.verticalLayout_3.addWidget(self.VolumeSlider)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 3, 1, 1)
        self.DurationSlider = QtWidgets.QSlider(self.centralwidget)
        self.DurationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.DurationSlider.setObjectName("DurationSlider")
        self.gridLayout_2.addWidget(self.DurationSlider, 1, 1, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout.addWidget(self.prevButton)
        self.stop_PlayButton = QtWidgets.QPushButton(self.centralwidget)
        self.stop_PlayButton.setObjectName("stop_PlayButton")
        self.horizontalLayout.addWidget(self.stop_PlayButton)
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 2, 1, 1)
        self.randomButton = QtWidgets.QPushButton(self.centralwidget)
        self.randomButton.setObjectName("randomButton")
        self.gridLayout_2.addWidget(self.randomButton, 2, 3, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 1, 4, 2, 1)
        self.infButton = QtWidgets.QPushButton(self.centralwidget)
        self.infButton.setObjectName("infButton")
        self.gridLayout_2.addWidget(self.infButton, 2, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.SpeedSlider = QtWidgets.QSlider(self.centralwidget)
        self.SpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SpeedSlider.setObjectName("SpeedSlider")
        self.verticalLayout_2.addWidget(self.SpeedSlider)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 2)
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.gridLayout_2.addWidget(self.addButton, 0, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple_Player"))
        self.label.setText(_translate("MainWindow", "Громкость"))
        self.prevButton.setText(_translate("MainWindow", "Prev"))
        self.stop_PlayButton.setText(_translate("MainWindow", "Play"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.randomButton.setText(_translate("MainWindow", "Случайный"))
        self.infButton.setText(_translate("MainWindow", "Повтор"))
        self.label_2.setText(_translate("MainWindow", "Скорость воспроизведения"))
        self.addButton.setText(_translate("MainWindow", "Добавить аудио"))
